install:
  - 'git clone https://github.com/git-ftp/git-ftp.git'
  - 'cd git-ftp'
  - 'git checkout 1.1.0'
  - 'sudo make install'
script:
- 'git ftp push --user ${user} --passwd ${sn} ftp://ftp.ngu.in/pe'
